import { Box, Typography } from "@mui/material";

import Footer from "@/components/Footer/Footer";
import FooterBackground from "@/components/Footer/FooterBackground";
import Head from "next/head";
import Hero from "@/components/Hero/Hero";
import HeroBackground from "@/components/Hero/HeroBackground";
import Project from "@/components/Projects/Project";
import Resume from "@/components/Resume/Resume";
import ResumeBackground from "@/components/Resume/ResumeBackground";
import TitleText from "@/components/TitleText";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBackground>
        <Hero />
      </HeroBackground>
      <Box id="about" p="42px" display="flex" justifyContent="center">
        <Box display="flex" flexDirection="column" gap="42px" maxWidth="726px">
          <Box display="flex" flexDirection="column" gap="8px">
            <TitleText>Web Development</TitleText>
            <Typography fontSize="20px">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
              mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
              rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
              potenti. Maecenas cursus enim nunc, sed aliquam purus interdum at.
              Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
              condimentum purus imperdiet, viverra odio sed, venenatis ligula.
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
              volutpat est quis mattis sollicitudin.
            </Typography>
          </Box>
          <Box display="flex" flexDirection="column" gap="8px">
            <TitleText>Electrical Engineering</TitleText>
            <Typography fontSize="20px">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
              mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
              rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
              potenti. Maecenas cursus enim nunc, sed aliquam purus interdum at.
              Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
              condimentum purus imperdiet, viverra odio sed, venenatis ligula.
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
              volutpat est quis mattis sollicitudin.
            </Typography>
          </Box>
          <Box display="flex" flexDirection="column" gap="8px">
            <TitleText>Artificial Intelligence</TitleText>
            <Typography fontSize="20px">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
              mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
              rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
              potenti. Maecenas cursus enim nunc, sed aliquam purus interdum at.
              Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
              condimentum purus imperdiet, viverra odio sed, venenatis ligula.
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
              volutpat est quis mattis sollicitudin.
            </Typography>
          </Box>
        </Box>
      </Box>
      <ResumeBackground>
        <Resume />
      </ResumeBackground>
      <Box id="projects" p="42px" display="flex" justifyContent="center">
        <Box display="flex" flexDirection="column" maxWidth="726px">
          <Box pb="32px">
            <TitleText>Projects</TitleText>
          </Box>
          <Box display="flex" flexDirection="column" gap="16px">
            <Project
              title="Ultra low power smart lock"
              tag="Electrical engineering"
              overview="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
            mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
            rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
            potenti. Maecenas cursus enim nunc, sed aliquam purus interdum
            at. Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
            condimentum purus imperdiet, viverra odio sed, venenatis ligula.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Praesent volutpat est quis mattis sollicitudin."
              details={
                <Typography fontSize="18px">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
                  mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
                  rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
                  potenti. Maecenas cursus enim nunc, sed aliquam purus interdum
                  at. Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
                  condimentum purus imperdiet, viverra odio sed, venenatis
                  ligula. Lorem ipsum dolor sit amet, consectetur adipiscing
                  elit. Praesent volutpat est quis mattis sollicitudin.
                </Typography>
              }
            />
            <Project
              title="MRI registration"
              tag="Artificial intelligence"
              overview="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
          mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
          rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
          potenti. Maecenas cursus enim nunc, sed aliquam purus interdum
          at. Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
          condimentum purus imperdiet, viverra odio sed, venenatis ligula.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          Praesent volutpat est quis mattis sollicitudin."
              details={
                <Typography fontSize="18px">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
                  mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
                  rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
                  potenti. Maecenas cursus enim nunc, sed aliquam purus interdum
                  at. Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
                  condimentum purus imperdiet, viverra odio sed, venenatis
                  ligula. Lorem ipsum dolor sit amet, consectetur adipiscing
                  elit. Praesent volutpat est quis mattis sollicitudin.
                </Typography>
              }
            />
            <Project
              title="Electrocardiogram"
              tag="Electrical engineering"
              overview="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
        mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
        rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
        potenti. Maecenas cursus enim nunc, sed aliquam purus interdum
        at. Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
        condimentum purus imperdiet, viverra odio sed, venenatis ligula.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Praesent volutpat est quis mattis sollicitudin."
              details={
                <Typography fontSize="18px">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
                  mollis purus eget lacus dapibus vestibulum. Nunc neque ante,
                  rutrum sit amet rutrum vitae, dignissim at nulla. Suspendisse
                  potenti. Maecenas cursus enim nunc, sed aliquam purus interdum
                  at. Pellentesque quis gravida lacus. Sed nec cursus nibh. Sed
                  condimentum purus imperdiet, viverra odio sed, venenatis
                  ligula. Lorem ipsum dolor sit amet, consectetur adipiscing
                  elit. Praesent volutpat est quis mattis sollicitudin.
                </Typography>
              }
            />
          </Box>
        </Box>
      </Box>
      <FooterBackground>
        <Footer />
      </FooterBackground>
    </>
  );
}
