import { Box, Typography } from "@mui/material";

import Footer from "@/components/Footer/Footer";
import FooterBackground from "@/components/Footer/FooterBackground";
import Head from "next/head";
import Hero from "@/components/Hero/Hero";
import HeroBackground from "@/components/Hero/HeroBackground";
import Overview from "@/components/Overview/Overview";
import Project from "@/components/Projects/Project";
import Projects from "@/components/Projects/Projects";
import Resume from "@/components/Resume/Resume";
import ResumeBackground from "@/components/Resume/ResumeBackground";
import TitleText from "@/components/TitleText";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBackground>
        <Hero />
      </HeroBackground>
      <Overview />
      <ResumeBackground>
        <Resume />
      </ResumeBackground>
      <Projects />
      <FooterBackground>
        <Footer />
      </FooterBackground>
    </>
  );
}
